# Generated by Django 4.1.5 on 2023-01-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='curiosidades',
            field=models.TextField(null=True),
        ),
    ]
