# Generated by Django 4.1.5 on 2023-01-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_animal_curiosidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='imagen',
            field=models.ImageField(null=True, upload_to='animales'),
        ),
    ]
