# Generated by Django 4.1.5 on 2023-01-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_avatar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(null=True, upload_to='blogs'),
        ),
    ]
