# Generated by Django 4.1.5 on 2023-02-02 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
