# Generated by Django 4.1.5 on 2023-02-02 03:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_avatarprofile_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvatarProfile',
            new_name='Avatar',
        ),
    ]
